import:
  - ~/.config/alacritty/colors/onedark-hv.yml

window:
  padding:
    x: 10
    y: 10
  dynamic_padding: true
  decorations: buttonless

font:
  normal:
    family: Hack Nerd Font
    style: Regular
  bold:
    family: Hack Nerd Font
    style: Bold
  italic:
    family: Hack Nerd Font
    style: Italic
  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic
  size: 16.0

selection:
  save_to_clipboard: true

key_bindings:
  - { key: N, mods: Command, action: CreateNewWindow }
