import:
  - ~/.config/alacritty/colors/onedark-hv.yml

window:
  padding:
    x: 10
    y: 10
  dynamic_padding: true
  decorations: buttonless
  dimensions:
    columns: 90
    lines: 24

font:
  normal:
    family: Hack
    style: Regular
  bold:
    family: Hack
    style: Regular
  italic:
    family: Hack
    style: Italic
  bold_italic:
    family: Hack
    style: Bold Italic
  size: 15.0
  offset:
    x: 0
    y: 10
  glyph_offset:
    x: 0
    y: 5

selection:
  save_to_clipboard: true

key_bindings:
  - { key: N, mods: Command, action: CreateNewWindow }
