#!/usr/bin/env bash

set -e
set -x

# === Copy dotfiles

dotfiles_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

if ! [[ -d ~/.config ]]; then
  mkdir ~/.config
fi

function print_success () { echo "  ✅ $1... done!"; }
function print_warning () { echo "  ⚠️  $1 config already present!"; }

echo

# Fish
if [[ -e ~/.config/fish ]]; then
  print_warning "Fish"
else
  ln -s $dotfiles_dir/config/fish/ ~/.config/fish
  print_success "Fish"
fi

# Kitty
if [[ -e ~/.config/kitty ]]; then
  print_warning "Kitty"
else
  ln -s $dotfiles_dir/config/kitty/ ~/.config/kitty
  print_success "Kitty"
fi

# Git
if [[ -e ~/.config/git ]]; then
  print_warning "Git"
else
  ln -s $dotfiles_dir/config/git/ ~/.config/git
  print_success "Git"
fi

# NeoVim
if [[ -e ~/.config/nvim ]]; then
  print_warning "NeoVim"
else
  ln -s $dotfiles_dir/config/nvim/ ~/.config/nvim
  print_success "NeoVim"
fi

# tmux
if [[ -e ~/.tmux.conf ]]; then
  print_warning "tmux"
else
  ln -s $dotfiles_dir/tmux.conf ~/.tmux.conf
  print_success "tmux"
fi

# Ruby
if [[ -e ~/.ruby-version ]]; then
  print_warning "Ruby"
else
  ln -s $dotfiles_dir/ruby-version ~/.ruby-version
  print_success "Ruby"
fi

echo
echo "✅ Dotfiles installed."



# === Install Kitty 

APPLICATIONS_DIR=~/Applications
TMP_INSTALL_DIR=dotfiles_install

cd $TMPDIR
if [[ -d $TMP_INSTALL_DIR ]]; then
  rm -R $TMP_INSTALL_DIR
fi
mkdir $TMP_INSTALL_DIR
cd $TMP_INSTALL_DIR

kitty_version="0.29.2"
kitty_url="https://github.com/kovidgoyal/kitty/releases/download/v$kitty_version"
kitty_dmg_filename="kitty-$kitty_version.dmg"

curl -L -O "$kitty_url/$kitty_dmg_filename"

curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin \
    installer=$kitty_dmg_filename \
    dest=$APPLICATIONS_DIR \
    launch=n

CURRENT_DIR=$(pwd)
cd $dotfiles_dir
rm -rf $CURRENT_DIR

echo "✅ Kitty installed."
