return {
  setup = function(lspconfig, on_attach, capabilities)
    lspconfig.tailwindcss.setup({
      filetypes = {
        "aspnetcorerazor",
        "astro",
        "astro-markdown",
        "blade",
        "clojure",
        "css",
        "django-html",
        "edge",
        "eelixir",
        "ejs",
        "elixir",
        "erb",
        "eruby",
        "gohtml",
        "gohtmltmpl",
        "haml",
        "handlebars",
        "hbs",
        "heex",
        "html",
        "html-eex",
        "htmldjango",
        "jade",
        "javascript",
        "javascriptreact",
        "leaf",
        "less",
        "liquid",
        "markdown",
        "mdx",
        "mustache",
        "njk",
        "nunjucks",
        "php",
        "postcss",
        "razor",
        "reason",
        "rescript",
        "ruby",
        "sass",
        "scss",
        "slim",
        "stylus",
        "sugarss",
        "svelte",
        "twig",
        "typescript",
        "typescriptreact",
        "vue",
      },
      on_attach = on_attach,
      capabilities = capabilities,
      settings = {
        tailwindCSS = {
          experimental = {
            classRegex = {
              "\\bclass:\\s*'([^']*)'",
              "\\bclass:\\s*\"([^\"]*)\"",
              "\\bclass=\\s*'([^']*)'",
              "\\bclass=\\s*\"([^\"]*)\"",
              { "\\bclasses\\(([^)]*)\\)", "\"([^\"]*)\"" },
              { "\\btokens\\(([^)]*)\\)",  "\"([^\"]*)\"" },
            },
          },
        },
      },
    })
  end,
}
